name: tweakwcs
channels:
    - http://ssb.stsci.edu/astroconda
    - conda-forge
dependencies:
    - python>=3.5
    - setuptools
    - numpy
    - numpydoc
    - astropy
    - graphviz
    - matplotlib
    - sphinx
    - pip:
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
      - gwcs
      - stsci.imagestats
      - stsci.stimage
      - spherical_geometry
      - git+https://github.com/spacetelescope/jwst#egg=jwst
